import * as T from '../vendor/three.module.js';
import {OrbitControls} from '../vendor/OrbitControls.js';
import {surface,material,walls,addFurniture,contains} from './appearance.js';
import {addArchitecture,roofElevation} from './architecture.js';
import {addStairConnection} from './transport.js';
import {loadState,saveState,isBuildingVisible,floorOffsets,hiddenDistricts,createMask,districtTint} from './visibility.js';
const $=id=>document.getElementById(id),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const displayName=(name,fallback='未命名空间')=>String(name??'').trim()||fallback;
const aliases={B2:'LG',B1:'G',F1:'F1',F2:'F2'},ids={ROOF:'ROOF',LG:'B2',G:'B1',F1:'F1',F2:'F2'},light={elevator:'#fff15c',up:'#ff545a',down:'#17845b'};
const href=(type,id='',query={})=>'#/'+type+(id?'/'+id:'')+(Object.keys(query).length?'?'+new URLSearchParams(query):'');
let data,route,renderer,camera,controls,scene,model,targets=[],labels=[],masks=new Map(),offsets={},state=loadState(localStorage),districtLevel=1,topView=false,visibleBounds=[];
function notice(s){$('notice').textContent=s;$('notice').hidden=!s;}function applyEditorOverlay(map){
 try{
  const raw=JSON.parse(localStorage.getItem('eastshuimo-atlas-v1')||'null');
  if(!raw||raw.revision!==map.revision||!raw.changes||typeof raw.changes!=='object')return{data:map,linked:false};
  const changes=raw.changes,custom=Object.values(changes).filter(v=>v&&v.custom&&v.kind==='object'&&typeof v.floor==='string'&&Array.isArray(v.position)&&v.position.length===2);
  const floors=map.floors.map(f=>{
   const rooms=f.rooms.map(r=>({...r,...(changes[r.id]||{})})).filter(r=>r.mapVisible!==false);
   const objects=(f.objects||[]).map(r=>({...r,...(changes[r.id]||{})})).filter(r=>r.mapVisible!==false);
   return{...f,rooms,objects:[...objects,...custom.filter(r=>r.floor===f.id&&!objects.some(x=>x.id===r.id))]};
  });
  const districts=Array.isArray(raw.districts)&&raw.districts.length?map.districts.map(d=>{const x=raw.districts.find(v=>v&&v.id===d.id);return x?{...d,name:typeof x.name==='string'?x.name:d.name,notes:typeof x.notes==='string'?x.notes:d.notes,color:typeof x.color==='string'?x.color:d.color,...(x.geometryEdited&&Array.isArray(x.parts)?{parts:x.parts,surfaceParts:x.surfaceParts||x.parts,roomIds:Array.isArray(x.roomIds)?x.roomIds:d.roomIds}: {})}:d;}):map.districts;
  return{data:{...map,floors,districts},linked:true};
 }catch{return{data:map,linked:false};}
}

function persist(){if(!saveState(localStorage,state))notice('本机无法保存显示设置；地图仍可正常使用。');}
function parse(){const[path,q='']=location.hash.slice(1).split('?'),p=path.split('/').filter(Boolean),query=new URLSearchParams(q);let type=['floor','building'].includes(p[0])?p[0]:'overview',id=p[1];if(type==='building'&&!data.buildings.some(b=>b.id===Number(id)))type='overview';if(type==='floor'&&!ids[id])id='F1';const legacy=query.get('level'),focus=query.get('focus')||(type==='overview'&&legacy)||state.overviewFocus||'G';return{type,id,level:type==='overview'?'ROOF':legacy||'ROOF',focus:ids[focus]?focus:'G',room:query.get('room'),stop:query.get('stop'),district:query.get('district')};}
const yOf=fid=>route.type==='floor'?data.floors.find(f=>f.id===fid).elevation:offsets[fid];
const owned=p=>isBuildingVisible(p,state,route);
const roomById=id=>data.floors.flatMap(f=>f.rooms).find(r=>r.id===id);
function allowedFloors(){const cap=data.floors.find(f=>f.displayId===route.level)?.elevation??99;return data.floors.filter(f=>!state.hiddenFloors.includes(f.id)&&(route.type==='overview'||(route.type==='floor'?(route.id==='ROOF'?f.id==='F2':f.displayId===route.id):f.elevation<=cap)));}
function layerOpacity(fid){return route.type==='overview'&&(fid==='ROOF'?route.focus!=='ROOF':aliases[fid]!==route.focus)?.5:1;}
function visiblePosition(f,p){return p.parts?.find(q=>owned(q)&&masks.get(f.id)?.test(q.position))?.position||(owned(p)&&masks.get(f.id)?.test(p.position||[0,0])?p.position:null);}
function accepted(f,p){return !!visiblePosition(f,p);}
function isContinuousAtriumColumn(f,m){return route.type!=='floor'&&(data.atriums||[]).some(a=>owned(a)&&a.openingFloors.includes(f.id)&&(a.columns||[]).some(([x,z])=>Math.hypot(x-m.position[0],z-m.position[1])<.3));}
function registerRoofBounds(){const on=(route.type==='floor'&&route.id==='ROOF'||route.type==='overview'||route.type==='building'&&route.level==='ROOF')&&state.roofVisible!==false&&masks.has('F2');if(!on)return;const ps=(data.roofs||[]).flatMap(r=>r.parts.filter(p=>owned(p)&&masks.get('F2').test(p.position)));if(!ps.length)return;const xs=ps.flatMap(p=>p.polygon.map(q=>q[0])),zs=ps.flatMap(p=>p.polygon.map(q=>q[1])),y=roofElevation(data,state,yOf,route),h=Math.max(...(data.roofs||[]).map(r=>r.thickness||.18));visibleBounds.push({bounds:[Math.min(...xs),Math.min(...zs),Math.max(...xs),Math.max(...zs)],low:y,high:y+h});}
function focus(xy,fid){const target=new T.Vector3(xy[0],yOf(fid),xy[1]),offset=camera.position.clone().sub(controls.target).normalize().multiplyScalar(42);controls.target.copy(target);camera.position.copy(target).add(offset);controls.update();}
function detail(html){$('visibility-panel').hidden=true;$('detail').hidden=false;$('detail-body').innerHTML=html;}
function selectRoom(r){const f=data.floors.find(f=>f.id===r.floor),position=visiblePosition(f,r);if(!position){notice('该位置当前被隐藏，可在“显示范围”中恢复。');return;}detail(`<span class="eyebrow">${aliases[r.floor]} · ${escape(r.usage||'空间')}</span><h2>${escape(displayName(r.name))}</h2>${r.notes?`<p>${escape(r.notes)}</p>`:''}<a href="${href('floor',aliases[r.floor],{room:r.id})}">在 ${aliases[r.floor]} 层定位 ↗</a>${r.buildingIds.map(id=>`<a href="${href('building',id,{room:r.id})}">${escape(data.buildings.find(b=>b.id===id)?.name)} · ${id} 号楼 ↗</a>`).join('')}`);focus(position,r.floor);}
function selectBlock(block,f){detail(`<span class="eyebrow">${f.displayId} · 建筑体块</span><h2>${escape(displayName(block.name,'未命名建筑体块'))}</h2><p>${block.sourceRoomIds.length} 个空间</p><a href="${href('floor',f.displayId,{room:block.sourceRoomIds[0]||''})}">查看本层房间 ↗</a>${block.buildingIds.map(id=>`<a href="${href('building',id)}">进入 ${escape(data.buildings.find(b=>b.id===id)?.name)} ↗</a>`).join('')}<button id="hide-selected-block">隐藏这个体块</button>`);$('hide-selected-block').onclick=()=>{state.hiddenBlocks.push(block.id);persist();renderMap(false);};}
function selectDistrict(dt){detail(`<span class="eyebrow">${aliases[dt.floor]} · 分区</span><h2>${escape(displayName(dt.name,'未命名分区'))}</h2>${dt.notes?`<p>${escape(dt.notes)}</p>`:''}<p>着色范围 ${Math.round(dt.parts.reduce((n,p)=>n+(p.area||0),0))} m² · 关联 ${dt.roomIds.length} 个空间</p>${dt.parentId?`<a href="${href('floor',aliases[dt.floor],{district:dt.parentId})}">返回上级分区</a>`:''}${data.districts.filter(x=>x.parentId===dt.id).map(x=>`<a href="${href('floor',aliases[x.floor],{district:x.id})}">${escape(x.name)} ↗</a>`).join('')}`);const p=dt.parts[0]?.position;if(p&&masks.get(dt.floor)?.test(p))focus(p,dt.floor);}
function selectStop(s){detail(`<span class="eyebrow">${aliases[s.floor]} · 跨层交通</span><h2>${s.kind==='elevator'?'电梯':'楼梯'}</h2>${s.connections.length?s.connections.map(c=>`<a href="${href('floor',aliases[c.targetFloor],{stop:c.targetStop})}"><span style="color:${s.kind==='elevator'?light.elevator:light[c.direction]}">${c.direction==='up'?'↑':'↓'}</span> 前往 ${aliases[c.targetFloor]} ↗</a>`).join(''):'<p>相邻层入口尚待核对</p>'}`);focus(s.position,s.floor);}
function addLabel(text,xy,fid,height,click,kind,priority=0){if(!String(text??'').trim()||!masks.get(fid)?.test(xy))return;const el=document.createElement('button');el.className='map-label'+(kind?' transport':'');el.textContent=text;if(kind)el.style.setProperty('--light',light[kind]);el.onclick=click;$('labels').append(el);labels.push({el,position:new T.Vector3(xy[0],yOf(fid)+height,xy[1]),priority});}
function dispose(){if(model){scene.remove(model);const gs=new Set(),ms=new Set();model.traverse(o=>{if(o.geometry)gs.add(o.geometry);if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material])ms.add(m);});for(const g of gs)g.dispose();for(const m of ms)m.dispose();}for(const m of masks.values()){m.texture.dispose();m.districtTexture?.dispose();}masks.clear();model=new T.Group();scene.add(model);targets=[];labels=[];visibleBounds=[];$('labels').replaceChildren();}
function add(group,mesh,type,item,f){if(!mesh)return;group.add(mesh);if(type){mesh.userData={type,item,floor:f};targets.push(mesh);}}
function namedMeshes(name){let count=0;model?.traverse(o=>{if(o.name===name)count++;});return count;}
function districtTintedMeshes(){let count=0;model?.traverse(o=>{const materials=o.material?(Array.isArray(o.material)?o.material:[o.material]):[];if(materials.some(m=>m.userData?.districtTint))count++;});return count;}
 function buildVisibilityPanel(){const box=$('visibility-content');box.replaceChildren();const dh=hiddenDistricts(data,state);function section(title,items,key,idOf=x=>x.id,labelOf=x=>x.name){const details=document.createElement('details');details.open=['楼层','楼栋'].includes(title);const summary=document.createElement('summary');summary.textContent=title;details.append(summary);for(const it of items){const id=idOf(it),label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.checked=!state[key].includes(id);if(key==='hiddenDistricts'&&it.parentId&&dh.has(it.parentId)){input.checked=false;input.disabled=true;}input.onchange=()=>{state[key]=input.checked?state[key].filter(v=>v!==id):[...new Set([...state[key],id])];persist();renderMap(false);};label.append(input,document.createTextNode(labelOf(it)));if(it.level>1&&key==='hiddenDistricts')label.style.paddingLeft=`${(it.level-1)*14}px`;details.append(label);}box.append(details);}for(const[key,title]of[['roofVisible','屋顶（3层）'],['groundVisible','F1 石板场地地面']]){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.checked=state[key]!==false;input.onchange=()=>{state[key]=input.checked;persist();renderMap(false);};label.append(input,document.createTextNode(title));box.append(label);}section('楼层',data.floors,'hiddenFloors',f=>f.id,f=>f.displayId);section('楼栋',data.buildings,'hiddenBuildings',b=>b.id,b=>`${b.id} ${b.name}`);for(const f of data.floors)section(`${f.displayId} 分区`,data.districts.filter(dt=>dt.floor===f.id),'hiddenDistricts');section('连续建筑体块',data.floors.flatMap(f=>f.overview.map((b,i)=>({...b,title:`${f.displayId} ${b.name} · ${i+1}`}))),'hiddenBlocks',b=>b.id,b=>b.title);}
function renderMapLegacy(resetCamera=true){
 const panelWasOpen=!$('visibility-panel').hidden;dispose();route=parse();if(route.type==='floor'){const maxLevel=Math.max(1,...data.districts.filter(d=>aliases[d.floor]===route.id).map(d=>d.level));districtLevel=Math.min(districtLevel,maxLevel);$('district-level').value=String(districtLevel);for(const opt of $('district-level').options)opt.disabled=Number(opt.value)>maxLevel;}offsets=floorOffsets(data,state);const overview=route.type==='overview',roofOnly=route.type==='floor'&&route.id==='ROOF',floors=allowedFloors();
 document.querySelector('footer').hidden=route.type==='floor';$('context').textContent=route.type==='building'?`${route.id} 号 · ${data.buildings.find(b=>b.id===Number(route.id)).name}`:route.type==='floor'?(roofOnly?'屋顶（3层）':`${route.id} 层`):'总览';$('slice-controls').hidden=route.type==='floor';$('expand-toggle').hidden=route.type==='floor';$('expand-toggle').textContent=state.expanded?'缩合':'展开';$('expand-toggle').setAttribute('aria-pressed',String(state.expanded));$('whole-building').hidden=route.type!=='building';$('district-control').hidden=route.type!=='floor'||roofOnly;$('detail').hidden=true;$('interiors-toggle').setAttribute('aria-pressed',String(state.interiors[route.type]));$('labels-toggle').setAttribute('aria-pressed',String(state.labels));$('legend-toggle').setAttribute('aria-pressed',String(state.legend));$('legend').hidden=!state.legend;for(const el of $('legend').querySelectorAll(':scope > span'))if(/向上|向下/.test(el.textContent))el.hidden=route.type!=='floor'&&!state.expanded;
 document.querySelectorAll('#navigation a').forEach(a=>a.classList.toggle('active',a.dataset.type===route.type&&a.dataset.id===route.id));$('nav-overview').classList.toggle('active',overview);for(const b of $('levels').children)b.classList.toggle('active',b.dataset.floor===route.level);
 for(const f of floors){const mask=createMask(f,data,state,route);if(route.type==='floor')mask.districtTexture=districtTint(f,data,state,districtLevel);masks.set(f.id,mask);if(!mask.visibleBounds)continue;const group=new T.Group();group.name=f.displayId;group.position.y=yOf(f.id);model.add(group);visibleBounds.push({bounds:mask.visibleBounds,low:yOf(f.id)-.18,high:yOf(f.id)+(f.storyHeight||3.6)+.18});if(roofOnly)continue;const height=(f.storyHeight||3.6)-.18,mats=Object.fromEntries(['wood','stone','green','wall','glass','brick'].map(k=>[k,material(k,mask)]));
  const fp=f.floorParts.filter(owned);for(const lift of new Set(fp.map(p=>p.localElevation||0)))add(group,surface({parts:fp.filter(p=>(p.localElevation||0)===lift)},.18,mats.stone,lift-.18));
  for(const r of f.rooms){const ps=r.parts.filter(owned);for(const kind of new Set(ps.map(p=>p.surfaceMaterial||r.surfaceMaterial||'wood'))){const pieces=ps.filter(p=>(p.surfaceMaterial||r.surfaceMaterial||'wood')===kind);if(pieces.length)add(group,surface({...r,parts:pieces},0,mats[kind]||mats.wood,(r.localElevation||0)+.018),'room',r,f);}}
  if(overview)for(const b of f.overview){const ps=b.parts.filter(owned);if(ps.length)add(group,surface({...b,parts:ps},height,state.interiors.overview?[material('wood',mask,{transparent:true,opacity:0,depthWrite:false}),material('brick',mask,{transparent:true,opacity:.22,depthWrite:false})]:[mats.wood,mats.brick],.02),'block',b,f);}
   for(const shell of f.exteriorShells||[]){const ps=shell.parts.filter(owned),base=(shell.footprintParts||shell.parts).filter(owned);if(ps.length){const m=surface({parts:ps},height,[mats.wall,mats.brick],0);if(m)m.name='隐藏空间外壳';add(group,m);}if(base.length){const floor=surface({parts:base},.18,mats.wood,-.18),cap=surface({parts:base},.10,mats.wall,height-.10);if(floor)floor.name='隐藏空间保留底板';if(cap)cap.name='隐藏空间顶盖';add(group,floor);add(group,cap);}}
  if(!overview){add(group,walls(f.wallPieces.filter(p=>p.kind==='wall'&&owned(p)),height,'wall',mats.wall));add(group,walls(f.wallPieces.filter(p=>p.kind==='door'&&owned(p)),Math.min(2.3,height),'door',material('glass',mask,{color:0x6cadbf,opacity:.32})));const marks=f.markers.filter(m=>accepted(f,m)&&!isContinuousAtriumColumn(f,m));if(marks.length){const mesh=new T.InstancedMesh(new T.CylinderGeometry(.12,.12,height,8),material('marker',mask,{color:0x11171c,transparent:true,opacity:.24,depthWrite:false}),marks.length),dummy=new T.Object3D();marks.forEach((m,i)=>{dummy.position.set(m.position[0],height/2,m.position[1]);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);});group.add(mesh);}}
  add(group,walls(f.wallPieces.filter(p=>p.kind==='window'&&owned(p)),height,'window',mats.glass));if(state.interiors[route.type])addFurniture(group,(f.furnishings||[]).filter(it=>accepted(f,it)),mask);
  if(!overview)for(const r of(f.objects||[]).filter(r=>accepted(f,r))){const m=new T.Mesh(new T.SphereGeometry(.3,10,8),material('object',mask,{color:0x6edaca}));m.position.set(r.position[0],.55,r.position[1]);add(group,m,'room',r,f);if(r.labelVisible!==false)addLabel(r.name,r.position,f.id,1.4,()=>selectRoom(r),null,2);}
  if(route.type==='floor')for(const dt of data.districts.filter(x=>x.floor===f.id&&x.level<=districtLevel&&!hiddenDistricts(data,state).has(x.id))){if(dt.parts[0])addLabel(dt.name,dt.parts[0].position,f.id,height+.25,()=>selectDistrict(dt),null,dt.level===districtLevel?4:2);}
  const top=f===floors.at(-1);if(!overview&&(state.expanded||route.type==='floor'||top))for(const r of f.rooms.filter(r=>accepted(f,r))){if(r.labelVisible===false||!String(r.name??'').trim()||/^待核对|^空间/.test(r.name))continue;addLabel(r.name,visiblePosition(f,r),f.id,height+.2,()=>selectRoom(r),null,1);}
  if(overview&&top)for(const b of data.buildings){if(state.hiddenBuildings.includes(b.id))continue;const rr=f.rooms.flatMap(r=>r.parts.filter(p=>p.buildingIds?.includes(b.id)&&mask.test(p.position)));if(!rr.length)continue;const p=rr.sort((a,b)=>b.area-a.area)[0].position;addLabel(b.name,p,f.id,height+.4,()=>location.hash=href('building',b.id),null,6);}
  for(const s of f.transportStops.filter(s=>accepted(f,s))){const directional=route.type==='floor'||state.expanded,down=s.connections.length&&!s.connections.some(c=>c.direction==='up'),col=s.kind==='elevator'?0xfff15c:!directional?0x9cbdc5:down?0x16865a:0xff545a;const marker=new T.Mesh(new T.CylinderGeometry(.33,.33,.24,12),material('transport',mask,{color:col,emissive:col,emissiveIntensity:.8}));marker.position.set(s.position[0],.2,s.position[1]);add(group,marker,'transport',s,f);if(!directional&&!top)continue;if(s.kind==='elevator')addLabel('▣ 电梯',s.position,f.id,height+.15,()=>selectStop(s),'elevator',5);else if(!directional)addLabel('楼梯',s.position,f.id,height+.1,()=>selectStop(s),null,4);else if(s.connections.length)s.connections.forEach((c,i)=>{if(c.direction==='down'&&s.connections.some(x=>x.direction==='up')){const dot=new T.Mesh(new T.CylinderGeometry(.23,.23,.25,12),material('transport',mask,{color:0x16865a,emissive:0x16865a,emissiveIntensity:.8}));dot.position.set(s.position[0]+.55,.22,s.position[1]);add(group,dot,'transport',s,f);}addLabel(`${c.direction==='up'?'↑':'↓'} ${aliases[c.targetFloor]}`,[s.position[0]+i*1.7,s.position[1]],f.id,height+.1,()=>location.hash=href('floor',aliases[c.targetFloor],{stop:c.targetStop}),c.direction,5);});else addLabel('楼梯',s.position,f.id,height,()=>selectStop(s),'down',2);}
 }
 registerRoofBounds();if(route.type!=='floor')buildConnections(floors);addArchitecture(model,data,route,state,masks,yOf,owned);labels.sort((a,b)=>b.priority-a.priority);buildVisibilityPanel();$('visibility-panel').hidden=!panelWasOpen;$('district-list').replaceChildren();if(route.type==='floor')for(const dt of data.districts.filter(x=>aliases[x.floor]===route.id&&x.level<=districtLevel&&!hiddenDistricts(data,state).has(x.id))){const b=document.createElement('button');b.textContent=(dt.level<districtLevel?'底 · ':'')+displayName(dt.name,'未命名分区');b.style.paddingLeft=`${8+(dt.level-1)*10}px`;b.style.setProperty('--district-color',dt.color);b.onclick=()=>selectDistrict(dt);$('district-list').append(b);}
 if(resetCamera)reset();if(!visibleBounds.length)notice('当前范围全部隐藏，可点击“全部显示”恢复。');else notice('');if(resetCamera&&route.room){const r=roomById(route.room);if(r)selectRoom(r);}if(resetCamera&&route.stop){const s=data.floors.flatMap(f=>f.transportStops).find(s=>s.id===route.stop);if(s&&masks.get(s.floor)?.test(s.position))selectStop(s);}if(resetCamera&&route.district){const dt=data.districts.find(x=>x.id===route.district);if(dt){if(districtLevel!==dt.level){districtLevel=dt.level;$('district-level').value=String(dt.level);renderMap();return;}selectDistrict(dt);}}
  window.__eastshuimo={revision:data.revision,route:{...route},state:JSON.parse(JSON.stringify(state)),floorOffsets:{...offsets},roofElevation:roofElevation(data,state,yOf,route),visibleFloors:floors.map(f=>f.id),visibleBounds,meshCount:model.children.reduce((n,g)=>n+g.children.length,0),furnitureCount:floors.reduce((n,f)=>n+(state.interiors[route.type]?(f.furnishings||[]).filter(it=>accepted(f,it)).length:0),0),roofMeshes:model.children.filter(m=>m.name.startsWith('屋顶 ·')).length,atriumMeshes:model.children.filter(m=>m.name==='贯通天井').length,groundMeshes:model.children.filter(m=>m.name==='透明场地地面').length,hiddenShells:namedMeshes('隐藏空间外壳'),hiddenShellFloors:namedMeshes('隐藏空间保留底板'),hiddenShellCaps:namedMeshes('隐藏空间顶盖'),districtTintedMeshes:districtTintedMeshes(),districtLevel,displayedDistrictIds:route.type==='floor'?data.districts.filter(d=>aliases[d.floor]===route.id&&d.level<=districtLevel&&!hiddenDistricts(data,state).has(d.id)).map(d=>d.id):[],transportStops:floors.flatMap(f=>f.transportStops.filter(s=>accepted(f,s)).map(s=>({id:s.id,kind:s.kind,floor:s.floor,position:s.position,connections:s.connections.length}))),connectionCount:model.children.filter(m=>['连续楼梯','电梯连接'].includes(m.name)).length,renderCalls:()=>renderer.info.render.calls};
}
function renderMap(resetCamera=true){
 const panelWasOpen=!$('visibility-panel').hidden;
 dispose();route=parse();
 if(route.type==='overview'&&state.overviewFocus!==route.focus){state.overviewFocus=route.focus;persist();}
 if(route.type==='floor'){
  const maxLevel=Math.max(1,...data.districts.filter(d=>aliases[d.floor]===route.id).map(d=>d.level));
  districtLevel=Math.min(districtLevel,maxLevel);$('district-level').value=String(districtLevel);
  for(const opt of $('district-level').options)opt.disabled=Number(opt.value)>maxLevel;
 }
 offsets=floorOffsets(data,state);
 const overview=route.type==='overview',roofOnly=route.type==='floor'&&route.id==='ROOF',floors=allowedFloors();
 const wallHeightScale=route.type!=='floor'&&state.expanded?.25:1;
 document.querySelector('footer').hidden=route.type==='floor';
 $('context').textContent=route.type==='building'?`${route.id} 号 · ${data.buildings.find(b=>b.id===Number(route.id)).name}`:route.type==='floor'?(roofOnly?'屋顶（3层）':`${route.id} 层`):`总览 · 聚焦 ${route.focus}`;
 $('slice-controls').hidden=route.type==='floor';$('expand-toggle').hidden=route.type==='floor';
 $('expand-toggle').textContent=state.expanded?'缩合':'展开';$('expand-toggle').setAttribute('aria-pressed',String(state.expanded));
 $('whole-building').hidden=route.type!=='building';$('district-control').hidden=route.type!=='floor'||roofOnly;$('detail').hidden=true;
 $('interiors-toggle').setAttribute('aria-pressed',String(state.interiors[route.type]));$('labels-toggle').setAttribute('aria-pressed',String(state.labels));$('legend-toggle').setAttribute('aria-pressed',String(state.legend));$('legend').hidden=!state.legend;
 for(const el of $('legend').querySelectorAll(':scope > span'))if(/向上|向下/.test(el.textContent))el.hidden=route.type!=='floor'&&!state.expanded;
 document.querySelectorAll('#navigation a').forEach(a=>a.classList.toggle('active',a.dataset.type===route.type&&a.dataset.id===route.id));$('nav-overview').classList.toggle('active',overview);
 for(const b of $('levels').children)b.classList.toggle('active',b.dataset.floor===(overview?route.focus:route.level));

 for(const f of floors){
  const mask=createMask(f,data,state,route);if(route.type==='floor')mask.districtTexture=districtTint(f,data,state,districtLevel);masks.set(f.id,mask);if(!mask.visibleBounds)continue;
  const group=new T.Group();group.name=f.displayId;group.position.y=yOf(f.id);model.add(group);
  const fullHeight=(f.storyHeight||3.6)-.18,wallHeight=fullHeight*wallHeightScale,alpha=layerOpacity(f.id);
  const mat=(kind,options={})=>{const base=options.opacity??(kind==='glass'?.48:1),opacity=base*alpha;return material(kind,mask,{...options,opacity,transparent:opacity<1,depthWrite:opacity>=.999});};
  const mats=Object.fromEntries(['wood','stone','green','wall','glass','brick','underground'].map(k=>[k,mat(k)]));
  visibleBounds.push({bounds:mask.visibleBounds,low:yOf(f.id)-.18,high:yOf(f.id)+wallHeight+.18});if(roofOnly)continue;

  const fp=f.floorParts.filter(owned);
  for(const lift of new Set(fp.map(p=>p.localElevation||0)))add(group,surface({parts:fp.filter(p=>(p.localElevation||0)===lift)},.18,mats.stone,lift-.18));
  for(const r of f.rooms){
   const ps=r.parts.filter(owned);
   for(const kind of new Set(ps.map(p=>p.surfaceMaterial||r.surfaceMaterial||'wood'))){
    const pieces=ps.filter(p=>(p.surfaceMaterial||r.surfaceMaterial||'wood')===kind);
    if(pieces.length)add(group,surface({...r,parts:pieces},0,mats[kind]||mats.wood,(r.localElevation||0)+.018),'room',r,f);
   }
  }
  const facade=f.id==='B2'||f.id==='B1'?'underground':'brick';
  if(overview)for(const b of f.overview){const ps=b.parts.filter(owned);if(ps.length)add(group,surface({...b,parts:ps},wallHeight,[mats.wood,mats[facade]],.02),'block',b,f);}
  for(const shell of f.exteriorShells||[]){
   const ps=shell.parts.filter(owned),base=(shell.footprintParts||shell.parts).filter(owned);
   if(ps.length){const m=surface({parts:ps},wallHeight,[mats.wall,mats[facade]],0);if(m)m.name='隐藏空间外壳';add(group,m);}
   if(base.length){const floor=surface({parts:base},.18,mats.wood,-.18),cap=surface({parts:base},.10,mats.wall,Math.max(0,wallHeight-.10));if(floor)floor.name='隐藏空间保留底板';if(cap)cap.name='隐藏空间顶盖';add(group,floor);add(group,cap);}
  }
  if(!overview){
   add(group,walls(f.wallPieces.filter(p=>p.kind==='wall'&&owned(p)),wallHeight,'wall',mats.wall));
   add(group,walls(f.wallPieces.filter(p=>p.kind==='door'&&owned(p)),Math.min(2.3,wallHeight),'door',mat('glass',{color:0x6cadbf,opacity:.32})));
   const marks=f.markers.filter(m=>accepted(f,m)&&!isContinuousAtriumColumn(f,m));
   if(marks.length){const mesh=new T.InstancedMesh(new T.CylinderGeometry(.12,.12,wallHeight,8),mat('marker',{color:0x11171c,opacity:.24}),marks.length),dummy=new T.Object3D();marks.forEach((m,i)=>{dummy.position.set(m.position[0],wallHeight/2,m.position[1]);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);});group.add(mesh);}
  }
  add(group,walls(f.wallPieces.filter(p=>p.kind==='window'&&owned(p)),wallHeight,'window',mats.glass));
  const railing=walls(f.wallPieces.filter(p=>(p.kind==='railing'||p.boundaryRole==='low-glass-railing')&&owned(p)),fullHeight,'window',mat('glass',{color:0x79b9e4,opacity:.42}));if(railing)railing.name='挖空边缘玻璃护栏';add(group,railing);
  if(state.interiors[route.type])addFurniture(group,(f.furnishings||[]).filter(it=>accepted(f,it)),mask,alpha);
  if(!overview)for(const r of(f.objects||[]).filter(r=>accepted(f,r))){const m=new T.Mesh(new T.SphereGeometry(.3,10,8),mat('object',{color:0x6edaca}));m.position.set(r.position[0],.55,r.position[1]);add(group,m,'room',r,f);if(r.labelVisible!==false)addLabel(r.name,r.position,f.id,1.4,()=>selectRoom(r),null,2);}
  if(route.type==='floor')for(const dt of data.districts.filter(x=>x.floor===f.id&&x.level<=districtLevel&&!hiddenDistricts(data,state).has(x.id)))if(dt.parts[0])addLabel(dt.name,dt.parts[0].position,f.id,fullHeight+.25,()=>selectDistrict(dt),null,dt.level===districtLevel?4:2);
  const top=f===floors.at(-1),focusFloor=overview&&aliases[f.id]===route.focus;
  if(!overview&&(state.expanded||route.type==='floor'||top))for(const r of f.rooms.filter(r=>accepted(f,r))){if(r.labelVisible===false||!String(r.name??'').trim()||/^待核对|^空间/.test(r.name))continue;addLabel(r.name,visiblePosition(f,r),f.id,wallHeight+.2,()=>selectRoom(r),null,1);}
  if(focusFloor)for(const b of data.buildings){if(state.hiddenBuildings.includes(b.id))continue;const rr=f.rooms.flatMap(r=>r.parts.filter(p=>p.buildingIds?.includes(b.id)&&mask.test(p.position)));if(!rr.length)continue;const p=rr.sort((a,b)=>b.area-a.area)[0].position;addLabel(b.name,p,f.id,wallHeight+.4,()=>location.hash=href('building',b.id),null,8);}
  for(const s of f.transportStops.filter(s=>accepted(f,s))){
   const directional=route.type==='floor'||state.expanded,down=s.connections.length&&!s.connections.some(c=>c.direction==='up'),col=s.kind==='elevator'?0xfff15c:!directional?0x9cbdc5:down?0x16865a:0xff545a;
   const marker=new T.Mesh(new T.CylinderGeometry(.33,.33,.24,12),mat('transport',{color:col,emissive:col,emissiveIntensity:.8}));marker.position.set(s.position[0],.2,s.position[1]);add(group,marker,'transport',s,f);
   const priority=focusFloor?12:5;if(!directional&&!top)continue;
   if(s.kind==='elevator')addLabel('▣ 电梯',s.position,f.id,wallHeight+.15,()=>selectStop(s),'elevator',priority);
   else if(!directional)addLabel('楼梯',s.position,f.id,wallHeight+.1,()=>selectStop(s),null,priority);
   else if(s.connections.length)s.connections.forEach((c,i)=>{if(c.direction==='down'&&s.connections.some(x=>x.direction==='up')){const dot=new T.Mesh(new T.CylinderGeometry(.23,.23,.25,12),mat('transport',{color:0x16865a,emissive:0x16865a,emissiveIntensity:.8}));dot.position.set(s.position[0]+.55,.22,s.position[1]);add(group,dot,'transport',s,f);}addLabel(`${c.direction==='up'?'↑':'↓'} ${aliases[c.targetFloor]}`,[s.position[0]+i*1.7,s.position[1]],f.id,wallHeight+.1,()=>location.hash=href('floor',aliases[c.targetFloor],{stop:c.targetStop}),c.direction,priority);});
   else addLabel('楼梯',s.position,f.id,wallHeight,()=>selectStop(s),'down',2);
  }
 }
 registerRoofBounds();if(route.type!=='floor')buildConnections(floors);
 addArchitecture(model,data,route,state,masks,yOf,owned,layerOpacity);
 labels.sort((a,b)=>b.priority-a.priority);buildVisibilityPanel();$('visibility-panel').hidden=!panelWasOpen;$('district-list').replaceChildren();
 if(route.type==='floor')for(const dt of data.districts.filter(x=>aliases[x.floor]===route.id&&x.level<=districtLevel&&!hiddenDistricts(data,state).has(x.id))){const b=document.createElement('button');b.textContent=(dt.level<districtLevel?'底 · ':'')+displayName(dt.name,'未命名分区');b.style.paddingLeft=`${8+(dt.level-1)*10}px`;b.style.setProperty('--district-color',dt.color);b.onclick=()=>selectDistrict(dt);$('district-list').append(b);}
 if(resetCamera)reset();if(!visibleBounds.length)notice('当前范围全部隐藏，可点击“全部显示”恢复。');else notice('');
 if(resetCamera&&route.room){const r=roomById(route.room);if(r)selectRoom(r);}if(resetCamera&&route.stop){const s=data.floors.flatMap(f=>f.transportStops).find(s=>s.id===route.stop);if(s&&masks.get(s.floor)?.test(s.position))selectStop(s);}if(resetCamera&&route.district){const dt=data.districts.find(x=>x.id===route.district);if(dt){if(districtLevel!==dt.level){districtLevel=dt.level;$('district-level').value=String(dt.level);renderMap();return;}selectDistrict(dt);}}
 const direct=data.connections.filter(c=>c.transportRole==='outdoor-direct-F1-LG'||c.skipsFloors?.includes('B1'));
 window.__eastshuimo={revision:data.revision,route:{...route},state:JSON.parse(JSON.stringify(state)),floorOffsets:{...offsets},floorOpacities:Object.fromEntries([...data.floors.map(f=>[f.id,layerOpacity(f.id)]),['ROOF',layerOpacity('ROOF')]]),wallHeightScale,roofElevation:roofElevation(data,state,yOf,route),visibleFloors:floors.map(f=>f.id),visibleBounds,meshCount:model.children.reduce((n,g)=>n+g.children.length,0),furnitureCount:floors.reduce((n,f)=>n+(state.interiors[route.type]?(f.furnishings||[]).filter(it=>accepted(f,it)).length:0),0),roofMeshes:model.children.filter(m=>m.name.startsWith('屋顶 ·')).length,atriumMeshes:model.children.filter(m=>m.name==='贯通天井').length,groundMeshes:model.children.filter(m=>m.name==='F1 石板场地地面').length,railingMeshes:namedMeshes('挖空边缘玻璃护栏'),hiddenShells:namedMeshes('隐藏空间外壳'),hiddenShellFloors:namedMeshes('隐藏空间保留底板'),hiddenShellCaps:namedMeshes('隐藏空间顶盖'),districtTintedMeshes:districtTintedMeshes(),districtLevel,displayedDistrictIds:route.type==='floor'?data.districts.filter(d=>aliases[d.floor]===route.id&&d.level<=districtLevel&&!hiddenDistricts(data,state).has(d.id)).map(d=>d.id):[],transportStops:floors.flatMap(f=>f.transportStops.filter(s=>accepted(f,s)).map(s=>({id:s.id,kind:s.kind,floor:s.floor,position:s.position,connections:s.connections.length}))),directF1LGConnections:direct.map(c=>c.id),connectionCount:model.children.filter(m=>['连续楼梯','电梯连接'].includes(m.name)).length,renderCalls:()=>renderer.info.render.calls};
}

function buildConnections(floors){const floorIds=new Set(floors.map(f=>f.id));for(const c of data.connections){if(!floorIds.has(c.fromFloor)||!floorIds.has(c.toFloor)||!owned(c)||!masks.get(c.fromFloor)?.test(c.fromPosition)||!masks.get(c.toFloor)?.test(c.toPosition))continue;const[x,z]=c.fromPosition,[xx,zz]=c.toPosition,low=yOf(c.fromFloor),high=yOf(c.toFloor),h=high-low;
  if(c.kind==='elevator'){const mesh=new T.Mesh(new T.BoxGeometry(1.15,h,1.15),material('glass',null,{color:0xffed63,emissive:0x8f7a13,emissiveIntensity:.3,opacity:.30}));mesh.position.set((x+xx)/2,(low+high)/2,(z+zz)/2);mesh.name='电梯连接';model.add(mesh);}
  else{const stop=data.floors.flatMap(f=>f.transportStops).find(s=>s.id===c.fromStop);if(stop)addStairConnection(model,c,stop,low,high,state.expanded);}
 }
 if(!data.atriums?.length&&state.expanded)for(let i=0;i<data.floors.length-1;i++){const f=data.floors[i],next=data.floors[i+1];if(!floorIds.has(f.id)||!floorIds.has(next.id))continue;const lower=[...(f.voids||[]),...f.rooms.filter(r=>r.usage==='庭院')],upper=next.voids||[];for(const a of lower){if(!owned(a))continue;const p=a.parts?.[0],pos=p?.position||a.position;if(!p||!pos)continue;const b=upper.find(b=>owned(b)&&b.parts.some(q=>contains(q,pos)||p.polygon.some(pt=>contains(q,pt))));if(!b)continue;const boundary=p.polygon,low=yOf(f.id)+(f.storyHeight||3.6)-.18,high=yOf(next.id);if(high<=low)continue;const verts=[];for(let j=0;j<boundary.length;j++){const[x,z]=boundary[j],[xx,zz]=boundary[(j+1)%boundary.length];if(!masks.get(f.id)?.test([x,z])&&!masks.get(next.id)?.test([x,z]))continue;verts.push(x,low,z,xx,low,zz,xx,high,zz,x,low,z,xx,high,zz,x,high,z);}if(!verts.length)continue;const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(verts,3));geo.computeVertexNormals();const mesh=new T.Mesh(geo,material('glass',null,{opacity:.15}));mesh.name='天井玻璃连接';model.add(mesh);}}
}
function reset(){if(!visibleBounds.length)return;const b=new T.Box3();for(const v of visibleBounds){b.expandByPoint(new T.Vector3(v.bounds[0],v.low,v.bounds[1]));b.expandByPoint(new T.Vector3(v.bounds[2],v.high,v.bounds[3]));}const size=b.getSize(new T.Vector3()),center=b.getCenter(new T.Vector3());camera.setViewOffset(innerWidth,innerHeight,innerWidth>900?-80:-35,0,innerWidth,innerHeight);controls.target.copy(center);const dist=Math.max(size.x/camera.aspect,size.z,size.y*.9)*1.85+22;camera.position.set(center.x+dist*(topView?0:.12),center.y+dist*(topView?1:.5),center.z+dist*(topView?.001:.96));controls.update();}
function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera);const occupied=[];for(const l of labels){const v=l.position.clone().project(camera),x=(v.x*.5+.5)*innerWidth,y=(-v.y*.5+.5)*innerHeight,show=state.labels&&v.z<1&&x>20&&x<innerWidth-20&&y>85&&y<innerHeight-95&&!occupied.some(([a,b])=>Math.abs(x-a)<78&&Math.abs(y-b)<23);l.el.hidden=!show;if(show){l.el.style.transform=`translate(${x}px,${y}px) translate(-50%,-100%)`;occupied.push([x,y]);}}}
async function readMapResponse(res,compressed){if(!res.ok)throw Error('地图数据读取失败');if(!compressed||res.headers.get('content-encoding')?.includes('gzip'))return res.json();if(typeof DecompressionStream==='undefined')throw Error('当前浏览器不支持地图数据解压');const stream=new Blob([await res.arrayBuffer()]).stream().pipeThrough(new DecompressionStream('gzip'));return JSON.parse(await new Response(stream).text());}
async function loadSplitMapData(){try{const rootResponse=await fetch(new URL('../data/map-v9-root.json.gz',import.meta.url));if(!rootResponse.ok)return null;const root=await readMapResponse(rootResponse,true),ids=Array.isArray(root.floorIds)?root.floorIds:['B2','B1','F1','F2'];delete root.floorIds;const floors=await Promise.all(ids.map(async id=>readMapResponse(await fetch(new URL('../data/map-floors-v9/'+id+'.json.gz',import.meta.url)),true)));return {...root,floors};}catch{return null;}}
async function loadMapData(){const split=await loadSplitMapData();if(split)return split;const compressed=await fetch(new URL('../data/map.json.gz',import.meta.url));if(compressed.ok)return readMapResponse(compressed,true);return readMapResponse(await fetch(new URL('../data/map.json',import.meta.url)),false);} 
async function start(){const loaded=applyEditorOverlay(await loadMapData());data=loaded.data;$('build-revision').textContent=(loaded.linked?'已关联后台 · ':'')+(data.revision?.split('-').slice(-2).join(' ')||'未标版本');renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true,logarithmicDepthBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.setClearColor('#111923');renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','可旋转和缩放的立体地图');$('scene').append(renderer.domElement);scene=new T.Scene();scene.add(new T.HemisphereLight(0xffffff,0x65727c,2.2));const sun=new T.DirectionalLight(0xffeee0,2.6);sun.position.set(-80,180,60);scene.add(sun);camera=new T.PerspectiveCamera(38,innerWidth/innerHeight,.1,2200);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=5;controls.maxDistance=1000;controls.maxPolarAngle=Math.PI*.49;
 $('buildings').innerHTML=data.buildings.map(b=>`<a data-type="building" data-id="${b.id}" href="${href('building',b.id)}"><b>${b.id}</b>${escape(b.name)}</a>`).join('');$('floor-links').innerHTML=data.floors.map(f=>`<a data-type="floor" data-id="${f.displayId}" href="${href('floor',f.displayId)}">${f.displayId}</a>`).join('');$('floor-links').insertAdjacentHTML('beforeend',`<a data-type="floor" data-id="ROOF" href="${href('floor','ROOF')}">屋顶（3层）</a>`);for(const f of [...data.floors,{displayId:'ROOF'}]){const b=document.createElement('button');b.textContent=f.displayId==='ROOF'?'屋顶（3层）':f.displayId;b.dataset.floor=f.displayId;b.onclick=()=>{if(route.type==='overview'){state.overviewFocus=f.displayId;persist();location.hash=href('overview','',{focus:f.displayId});}else location.hash=href(route.type,route.id,{level:f.displayId});};$('levels').append(b);}
 $('whole-building').onclick=()=>location.hash=href('building',route.id);$('expand-toggle').onclick=()=>{state.expanded=!state.expanded;persist();renderMap();};$('interiors-toggle').onclick=()=>{state.interiors[route.type]=!state.interiors[route.type];persist();renderMap(false);};$('visibility-toggle').onclick=()=>{$('visibility-panel').hidden=!$('visibility-panel').hidden;$('detail').hidden=true;};$('close-visibility').onclick=()=>$('visibility-panel').hidden=true;$('show-all').onclick=()=>{for(const k of ['hiddenFloors','hiddenBuildings','hiddenDistricts','hiddenBlocks'])state[k]=[];state.roofVisible=true;state.groundVisible=true;persist();renderMap();};$('reset').onclick=reset;$('labels-toggle').onclick=()=>{state.labels=!state.labels;persist();$('labels-toggle').setAttribute('aria-pressed',String(state.labels));};$('legend-toggle').onclick=()=>{state.legend=!state.legend;persist();$('legend').hidden=!state.legend;$('legend-toggle').setAttribute('aria-pressed',String(state.legend));};$('top-view').onclick=()=>{topView=!topView;$('top-view').classList.toggle('active',topView);reset();};$('close-detail').onclick=()=>$('detail').hidden=true;$('district-level').onchange=e=>{districtLevel=Number(e.target.value);renderMap(false);};$('capture').onclick=()=>{renderer.render(scene,camera);renderer.domElement.toBlob(blob=>{const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download='东水磨地图.png';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);});};for(const[button,target]of[['building-menu','buildings'],['floor-menu','floor-links']])$(button).onclick=()=>{$(target).hidden=!$(target).hidden;$(button).setAttribute('aria-expanded',String(!$(target).hidden));};
 const ray=new T.Raycaster();let down=[0,0];renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;ray.setFromCamera(new T.Vector2(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1),camera);const hit=ray.intersectObjects(targets,false).find(h=>masks.get(h.object.userData.floor.id)?.test([h.point.x,h.point.z]));if(!hit)return;const{type,item,floor}=hit.object.userData;if(route.type==='overview'&&aliases[floor.id]!==route.focus){state.overviewFocus=aliases[floor.id];persist();location.hash=href('overview','',{focus:aliases[floor.id]});return;}if(type==='room')selectRoom({...item,position:[hit.point.x,hit.point.z]});if(type==='block')selectBlock(item,floor);if(type==='transport')selectStop(item);});
 renderer.domElement.addEventListener('keydown',e=>{if(['+','=','-','0','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();if(e.key==='0')reset();else if(['+','=','-'].includes(e.key))camera.position.sub(controls.target).multiplyScalar(e.key==='-'?1.15:.87).add(controls.target);else{const v=new T.Vector3(e.key==='ArrowLeft'?-4:e.key==='ArrowRight'?4:0,0,e.key==='ArrowUp'?-4:e.key==='ArrowDown'?4:0);camera.position.add(v);controls.target.add(v);}}});window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});window.addEventListener('hashchange',()=>renderMap());window.addEventListener('storage',e=>{if(e.key==='eastshuimo-atlas-v1')location.reload();});renderMap();animate();notice('');}
start().catch(e=>{notice('无法载入地图：'+e.message);console.error(e);});
